// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// ローカル開発は .env.local を優先（本番値はローカルに置かない方針）。
// dotenv は既定で既存の env を上書きしないので、.env.local → .env の順に読めば
// .env.local が勝ち、足りない分だけ .env がフォールバックになる。
// 本番DBに対する操作は .env.local を使わず、その場で接続情報を渡して実行する。
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"], // マイグレーションはPgBouncer不可のため直接接続
  },
});
